// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminList: typeof import('./src/components/adminList.vue')['default']
    Aside: typeof import('./src/components/aside.vue')['default']
    Dashboard: typeof import('./src/components/dashboard.vue')['default']
    Goods: typeof import('./src/components/goods.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Icons: typeof import('./src/components/icons.vue')['default']
    Member: typeof import('./src/components/member.vue')['default']
    Order: typeof import('./src/components/order.vue')['default']
    SearchField: typeof import('./src/components/searchField.vue')['default']
    Upload_backup: typeof import('./src/components/upload_backup.vue')['default']
  }
}

export { }
