// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminList: typeof import('./components/adminList.vue')['default']
    Aside: typeof import('./components/aside.vue')['default']
    Dashboard: typeof import('./components/dashboard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Header: typeof import('./components/header.vue')['default']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpKey: typeof import('~icons/ep/key')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpPieChart: typeof import('~icons/ep/pie-chart')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    Upload_backup: typeof import('./components/upload_backup.vue')['default']
  }
}

export { }
