// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminList: typeof import('./components/adminList.vue')['default']
    Aside: typeof import('./components/aside.vue')['default']
    Card: typeof import('./components/card.vue')['default']
    Dashboard: typeof import('./components/dashboard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Goods: typeof import('./components/goods.vue')['default']
    Header: typeof import('./components/header.vue')['default']
    Icons: typeof import('./components/icons.vue')['default']
    Member: typeof import('./components/member.vue')['default']
    Order: typeof import('./components/order.vue')['default']
    SearchField: typeof import('./components/searchField.vue')['default']
    Upload_backup: typeof import('./components/upload_backup.vue')['default']
  }
}

export { }
